language: scala
sudo: false
scala:
- 2.11
script:
- sbt test
after_success:
- bash deploy.sh
env:
  global:
    secure: dE66dwQ4WlAFSyozoVNQ03ePu7mvZV0Hl3XiRrb8oSuEhN6TUhgi5wM9ecejN6z222dwKsO+QX/hjfJsdsYDD73GikB6giAUgAdRDoOBmXfhr+CWzSlDTWvn9nWmbuwKlWSdOG3oDvvtsdxW0PNXTUH9H4ui2Ycc3eF+RDDw3QHw2w9Ch/A2uGI4S1CmnfhJsfTyIc588AROvQItiAtrDh46d0kSSLhNO7oY6gFNAHYvN1R2E2AUu/X8jI/PqRl0LpESaUYDEZRUbRkEQKNtbMUp7CZikzHYMkAIKGUGgpmIxkGnoPAZpdIzkb2QVDbCZKqVKOiL9UJvW2qSLj1/UcRg53Kx+U5Hmn99Vdk4mbh2S9Cu75aScxZTRK+7Ilac2lOauaME5nsJ0Yyeg5+A3yRIjN/jaNsp7T/b9Go9Nf6NKhDc7hXGFGZVaXg0z0BXiuFbC3XpFS/D4RHIRg1SbwNf+sftXXGKYVkW5WNFByzL6+1jIDJhO+Ws3WfckDrdHp4T2leRnU2XLfV0PwkV9eEY44hPlQO01fTnVOijnNI6Fbw8GCxyZeEJHFIfWxLvkDoVGKs6ry6B8jjKFisZeU3c82uHl7/meEsci7rLmswGopOu2ovVNL7psOJ3RPpkJa3HTcKWS6Ra5nmAZiakg7tyZ2Hvq5i1U9nVubyPZvo=
