language: scala
sudo: false
jdk:
- oraclejdk8
scala:
- 2.12.0
install:
- sbt update
script:
- sbt test
- sbt doc
after_success:
- test $TRAVIS_PULL_REQUEST == "false" &&
  test $TRAVIS_BRANCH == "master" &&
  sbt publish &&
  bash deploy.sh
env:
  global:
  - secure: iQXzytYM049Bc+PvPO7h4xGYxqtHGwc+zU+EoJPmH2XYFJnnSAst3wFR75tSiXQIJLHycSZmm4uh44cJpyzWObb2NQwW8EQDg2znv8uQ92NKkcIIIVcM0Ito5fvlOn+rEbyRvZqO9rq9SxysR4MiTCDyH7UDNIOGX++SvCGX9JFenP5ha7u/TMU+EYK/eLIvbrzYZY8ULyUQggNwi6qQyaSxu0Ngx1s4Tv/KHUhw9/1MJi/sadR76kqVSaO6aZHdMiIWt+4LG++2ZjMkCCHM0BDJDPo3+TNyjCTDGvghQe+0QEjbgIzDHF+7hEHfWVqOpPcuxvqExwfWT7LU/B4jqQ+lhKc/28l9TQKtpVHFX788yd7oqiiivJXx0geI3Hs2IkpmzWJ91YlGlcNMLEqf0cs8dmYA5EHz7MFcl1oTXvdH722gEe3wBIyylPUZICbQ0HwjRgzAKvRt1K8eflis96y7GmDT2PHEKzNkZ/NfdK4qnEP9jTH1sqxKrbYiUJln72brOy0Q5vujcYtlh/s9mbY4QR1mRazB0cdZpkrmVC1SedYBnPiaQYRFAYjhfOEdxTVmr8pC+aGh9aEXobuJHUNamDWMThhUPkcQ+WQZ3283NCCsBZk2FYKFQ3zBn0K1agHPp2HDVK3i6hjMX58SZsIY/h/AjCUCo+cXcMebmWA=
  - secure: rOF9uaFHOl76ru+iuVPAZfHSCWVMlpEoX547b94SD02kJDMnMkvq6SZffiGXcjPBj7vnNA7nSRuPYFDDR8MtywuCSwXo/4RPbukael51huusfdeeHxzpY9jRM7LcTslGLxF0fd8nnAJX+4nHqSvRpDCnZjPoVolupSvoLqu8W7WhWrETGeNCJPXzFr54AphSHOJt0WDzdutnHgoHdf1+mtc7pFshMfxv+WjYDFipHONCM9RUWmcYV7/5LMZuWjtQingdhOmG5+rcH60QsCtVtvozFDIiZ1BPNckUPiWHhyt53Uj7KFbTopnOxA/Vzh+CYJqWKk8uD7DV6USwx56KzyMBBqiesRl4NuXLSDIaXFXqOD4HKQlPUnRAP1FVPQAPGCQsY0qzS2bBAiMbKYnShjqlQqqtCFuJoryPLAvsKu4+VDCkSAmOA0tWQEhIFtoWb0PfITM6JfYr9njkmmEXrsdO1P8S2VJUkRQZiamuB8OL6SaMQWYexqPAo101Kyn76e2cHg7ubxLXzP28Fi6HK7+IhYOOm+i2PPb6HbuJik7Dppp7W7gl7fuHA8y1gld2IAuY1GE0ev5lBMgE38p3FtPGoPWn/AM7KPtJmIz/ku5PHb1tt+FbRWk3AIW6QN32642sY4mrv2qOMLLq3Pe8T1C13BXKpkwoyUC9lYbnHY0=
  - secure: SnpR8aDdA2Y6Xbp5+QGnz1cPnKegguCjh863J9HPnegA/8SF+xLY5wLMtOMR02LVYHlKulA6N/bfoo7/5bfSjvDmtMkVjlt5N435H10JE6eBtiluvzOnjDZvh/jsUCVfjIPnPKcwkoJrYjqUpR7z+ekS+cNbiKgVUSPMoH6bY0oYvGTxFCeOkMQqxZIa5SwFMktCssLbf0yI2QAl10wUffoJ+Le/1tANnCc2pZVLPenK9AKXefZw9IvkL3rTM919fy0p5AsCEgoFWmyVvjZBt1W6groHR+ryNtwNBTDZii0KotaICmR3agTha+fHiVfgAHGHFsP+SYbEA0I3R7teYI759FsYGl0r7VLBpspfZLFGgYFkCzDOhkPXdNbXWvCtGlzEmU6T/m9wq5IEJWqkJ/tJiaSQz3GrGSRuYb+CJgwqgHT4+BwqtEhJHZZ5QGueHYs6++Ezh2XjG0hu2HzwCxkhpgu4Yiic0fIn2snWt8zhA7RwnEFqbUL9YN77dFisI4LJMYrugGSI5KsoXZ5mroVQjjCJ1f0q6L4WAL1mjffQWH4OiP/oDQIvoZFC/ECZAASpaJbS28iWv5iz/ZFDTWoTWhsNK67motRodZygZ0ZeB0RAaCDMJ5jW691jJueXaL/1wzAxyjdVFsmCfazk2y6+/vxA+TJsMnjbiOMiLLU=
