language: scala
sudo: false
jdk:
- oraclejdk8
scala:
- 2.12.0
script:
- sbt test
- sbt doc
after_success:
- test $TRAVIS_PULL_REQUEST == "false" &&
  test $TRAVIS_BRANCH == "master" &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", sys.env("SONATYPE_USERNAME"), sys.env("SONATYPE_PASSWORD"))' publish &&
  bash deploy.sh
