language: scala
sudo: false
jdk:
- oraclejdk8
scala:
- 2.12.0
install:
- sbt update
script:
- sbt test
- sbt doc
after_success:
- test $TRAVIS_PULL_REQUEST == "false" &&
  test $TRAVIS_BRANCH == "master" &&
  sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", $SONATYPE_NAME, $SONATYPE_PASS)' publish &&
  bash deploy.sh
